Repository shubham7668/WebDev, pull requests merged in 2022-10, with the labels that each got.

#4 added tailwind website
  tailwind_website/1.jpg
  tailwind_website/4.jpg
  tailwind_website/5.jpg
  tailwind_website/6.jpg
  tailwind_website/Bowker, Gordon.jpg
  tailwind_website/Safeimagekit-resized-imgpng.png
  tailwind_website/WhatsApp Image 2022-03-09 at 10.36.53 PM.jpeg
  tailwind_website/download.jpeg
  tailwind_website/feat_3.png
  tailwind_website/gerald-baldwin.jpg
  tailwind_website/girl.jpeg
  tailwind_website/ice.jpg
  tailwind_website/iced-caramel-macchiato.jpg
  tailwind_website/index.html
  tailwind_website/logo-instagram-png-13551.png
  tailwind_website/logo.png
  tailwind_website/meta.png
  tailwind_website/mocha.png
  tailwind_website/package-lock.json
  tailwind_website/package.json
  tailwind_website/postcss.config.js
  tailwind_website/pperment.png
  tailwind_website/starbucks-coffee-jubilee-hills-1613556641.jpg
  tailwind_website/styles.css
  tailwind_website/tailwind.config.js
  tailwind_website/twitter-icon-83.png
  tailwind_website/zev.webp
Labels: hacktoberfest-accepted

#8 Project
  SKDRCLASSES/1.jpeg
  SKDRCLASSES/2.jfif
  SKDRCLASSES/css/style.css
  SKDRCLASSES/gallery/10.jfif
  SKDRCLASSES/gallery/11.jfif
  SKDRCLASSES/gallery/12.jfif
  SKDRCLASSES/gallery/13.jfif
  SKDRCLASSES/gallery/3.jfif
  SKDRCLASSES/gallery/4.jfif
  SKDRCLASSES/gallery/5.jfif
  SKDRCLASSES/gallery/6.jfif
  SKDRCLASSES/gallery/7.jfif
  SKDRCLASSES/gallery/8.jfif
  SKDRCLASSES/gallery/9.jfif
  SKDRCLASSES/index.html
Labels: hacktoberfest-accepted, reviewed

#12 HACKTOBERFEST-2022
  STICKY NOTES/CRUD.html
Labels: hacktoberfest-accepted

#11 Adding styling & functionality to form wave
  Form Input Wave/script.js
  Form Input Wave/style.css
Labels: hacktoberfest-accepted

#14 Parallax Website
  Parallax Website/css/main.css
  Parallax Website/img/img1.jpeg
  Parallax Website/img/img2.jpeg
  Parallax Website/img/img3-2.jpeg
  Parallax Website/img/img3-3.jpeg
  Parallax Website/img/img3.jpeg
  Parallax Website/img/logo1.png
  Parallax Website/img/logo2.png
  Parallax Website/img/logo3.png
  Parallax Website/img/logo4.png
  Parallax Website/img/name.png
  Parallax Website/img/name2.png
  Parallax Website/img/name3.png
  Parallax Website/img/name4.png
  Parallax Website/img/quote1.png
  Parallax Website/img/quote2.png
  Parallax Website/img/quote3.png
  Parallax Website/img/quote4.png
  Parallax Website/img/quote5.png
  Parallax Website/img/quote6-a.png
  Parallax Website/img/quote6.png
  Parallax Website/index.html
Labels: hacktoberfest-accepted

#13 Added Netflix Homepage Clone
  Netflix Homepage Clone/Assets/android-icon-144x144.png
  Netflix Homepage Clone/Assets/android-icon-192x192.png
  Netflix Homepage Clone/Assets/android-icon-36x36.png
  Netflix Homepage Clone/Assets/android-icon-48x48.png
  Netflix Homepage Clone/Assets/android-icon-72x72.png
  Netflix Homepage Clone/Assets/android-icon-96x96.png
  Netflix Homepage Clone/Assets/apple-icon-114x114.png
  Netflix Homepage Clone/Assets/apple-icon-120x120.png
  Netflix Homepage Clone/Assets/apple-icon-144x144.png
  Netflix Homepage Clone/Assets/apple-icon-152x152.png
  Netflix Homepage Clone/Assets/apple-icon-180x180.png
  Netflix Homepage Clone/Assets/apple-icon-57x57.png
  Netflix Homepage Clone/Assets/apple-icon-60x60.png
  Netflix Homepage Clone/Assets/apple-icon-72x72.png
  Netflix Homepage Clone/Assets/apple-icon-76x76.png
  Netflix Homepage Clone/Assets/apple-icon-precomposed.png
  Netflix Homepage Clone/Assets/apple-icon.png
  Netflix Homepage Clone/Assets/browserconfig.xml
  Netflix Homepage Clone/Assets/favicon-16x16.png
  Netflix Homepage Clone/Assets/favicon-32x32.png
  Netflix Homepage Clone/Assets/favicon-96x96.png
  Netflix Homepage Clone/Assets/favicon.ico
  Netflix Homepage Clone/Assets/manifest.json
  Netflix Homepage Clone/Assets/ms-icon-144x144.png
  Netflix Homepage Clone/Assets/ms-icon-150x150.png
  Netflix Homepage Clone/Assets/ms-icon-310x310.png
  Netflix Homepage Clone/Assets/ms-icon-70x70.png
  Netflix Homepage Clone/Images/AAAABVxdX2WnFSp49eXb1do0euaj-F8upNImjofE77XStKhf5kUHG94DPlTiGYqPeYNtiox-82NWEK0Ls3CnLe3WWClGdiJP.png
  Netflix Homepage Clone/Images/IN-en-20210524-popsignuptwoweeks-perspective_alpha_website_large.jpg
  Netflix Homepage Clone/Images/device-pile-in.png
  Netflix Homepage Clone/Images/download-icon.gif
  Netflix Homepage Clone/Images/netflix-logo-png-2562.png
  Netflix Homepage Clone/Images/netflix_logo_icon_170919.ico
  Netflix Homepage Clone/Images/tv.png
  Netflix Homepage Clone/index.html
  Netflix Homepage Clone/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#16 project-added
  .vscode/settings.json
  Random-rectangle-generator-onMousecClick/attachBindings.js
  Random-rectangle-generator-onMousecClick/handlers.js
  Random-rectangle-generator-onMousecClick/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#26 Fixed #23 (Implemented automatic checks)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/checker.yml
  .github/workflows/contributors.yml
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted

#34 Create test5.txt
  test5.txt
Labels: in-review, hacktoberfest-accepted

#37 Dark switch added
  Projects/DarkSwitch/README.md
  Projects/DarkSwitch/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#21 Added my Responsive Landing Page website
  Projects/Responsive Landing Page/assets/shoe.jpeg
  Projects/Responsive Landing Page/assets/shoe2.jpeg
  Projects/Responsive Landing Page/assets/shoe3.jpeg
  Projects/Responsive Landing Page/assets/shoe4.jpeg
  Projects/Responsive Landing Page/css/main.css
  Projects/Responsive Landing Page/css/main.css.map
  Projects/Responsive Landing Page/css/main.scss
  Projects/Responsive Landing Page/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#42 added admin dashboard
  Projects/Admin Dashboard/assets/adminIcon.png
  Projects/Admin Dashboard/assets/css/style.css
  Projects/Admin Dashboard/assets/js/index.js
  Projects/Admin Dashboard/index.html
  Projects/Admin Dashboard/preview/darkmode.png
  Projects/Admin Dashboard/preview/lightmode.png
  Projects/Admin Dashboard/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#19 Project added
  Projects/typefast_touch_typing_site/index.html
  Projects/typefast_touch_typing_site/index.js
  Projects/typefast_touch_typing_site/style1.css
Labels: hacktoberfest-accepted, hacktoberfest

#44 whiteboard-writing-app
  Projects/whiteboard/.vscode/settings.json
  Projects/whiteboard/Readme.md
  Projects/whiteboard/index.html
  Projects/whiteboard/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#46 Build a Note Maker Web App using Html Css And Javascript
  Projects/Note Maker/Read.md
  Projects/Note Maker/Screenshot (14).png
  Projects/Note Maker/index.html
  Projects/Note Maker/index.js
  Projects/Note Maker/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#54 Add files via upload
  Projects/Gallery Webpage/index.html
  Projects/Gallery Webpage/styles.css
Labels: hacktoberfest

#61 Gallery for Cars Added
  Projects/Gallery for Cars/Audi.jpg
  Projects/Gallery for Cars/Bentley.jpg
  Projects/Gallery for Cars/Chevrolet.jpg
  Projects/Gallery for Cars/Fiat.png
  Projects/Gallery for Cars/Honda.jpg
  Projects/Gallery for Cars/Jaguar.jpg
  Projects/Gallery for Cars/Jeep.webp
  Projects/Gallery for Cars/Land-Rover.jpg
  Projects/Gallery for Cars/Lexus.jpg
  Projects/Gallery for Cars/PORSCHE.jpg
  Projects/Gallery for Cars/README.md
  Projects/Gallery for Cars/Volvo-car.jpg
  Projects/Gallery for Cars/app.json
  Projects/Gallery for Cars/bugatti.jpg
  Projects/Gallery for Cars/close.png
  Projects/Gallery for Cars/ford.jpg
  Projects/Gallery for Cars/gallery.js
  Projects/Gallery for Cars/gallery1.css
  Projects/Gallery for Cars/gallery2.css
  Projects/Gallery for Cars/hello.jpg
  Projects/Gallery for Cars/home.html
  Projects/Gallery for Cars/index.php
  Projects/Gallery for Cars/menu.png
  Projects/Gallery for Cars/mercedes-Benz.jpg
  Projects/Gallery for Cars/nissan.jpg
  Projects/Gallery for Cars/rolls-royce.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#67 Added Drum Player
  Projects/Drum Player/README.md
  Projects/Drum Player/images/crash.png
  Projects/Drum Player/images/kick.png
  Projects/Drum Player/images/snare.png
  Projects/Drum Player/images/tom1.png
  Projects/Drum Player/images/tom2.png
  Projects/Drum Player/images/tom3.png
  Projects/Drum Player/images/tom4.png
  Projects/Drum Player/index.html
  Projects/Drum Player/index.js
  Projects/Drum Player/sounds/crash.mp3
  Projects/Drum Player/sounds/kick-bass.mp3
  Projects/Drum Player/sounds/snare.mp3
  Projects/Drum Player/sounds/tom-1.mp3
  Projects/Drum Player/sounds/tom-2.mp3
  Projects/Drum Player/sounds/tom-3.mp3
  Projects/Drum Player/sounds/tom-4.mp3
  Projects/Drum Player/styles.css
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#71 Car Home Page added
  Projects/CarHomePage/README.md
  Projects/CarHomePage/app.json
  Projects/CarHomePage/close.png
  Projects/CarHomePage/home.html
  Projects/CarHomePage/homepage.css
  Projects/CarHomePage/index.php
  Projects/CarHomePage/kenny-eliason-orGJcWVI6js-unsplash.jpg
  Projects/CarHomePage/menu.png
Labels: hacktoberfest-accepted, hacktoberfest

#80 ADDED TWO GOOD BEGINNER FRIENDLY PROJECTS
  Projects/Codeclub/README.md
  Projects/Codeclub/about.html
  Projects/Codeclub/index.html
  Projects/Codeclub/members.html
  Projects/Codeclub/password.html
  Projects/Codeclub/password.js
  Projects/Codeclub/styles.css
  Projects/Game_of_Thrones/.vscode/settings.json
  Projects/Game_of_Thrones/Game_of_Thrones_title_card.jpg
  Projects/Game_of_Thrones/README.md
  Projects/Game_of_Thrones/gameofthrones-allseasons.jpg
  Projects/Game_of_Thrones/got.jpg
  Projects/Game_of_Thrones/index.html
  Projects/Game_of_Thrones/style.css
Labels: hacktoberfest-accepted, hacktoberfest
